name: flutter-me
services:
  nextjs:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextjs